services:
  bridge:
    build:
      context: .
      dockerfile: bridge/Dockerfile
    environment:
      ACCOUNTS_FILE: "/app/accounts/ACCOUNTS.DAT"
    volumes:
      - ./inbox:/app/inbox
      - ./processed:/app/processed
      - ./accounts:/app/accounts
    working_dir: /app
    stdin_open: true
    tty: true
