#!/bin/bash

echo "=== COBOL BANK ARCHITECTURE VIEW ==="

echo ""
echo "           INPUT LAYER"
echo "   trans_input.txt"
echo "          ||"
echo "          \/"
echo "   +-------------------+"
echo "   |  COBOL CORE       |"
echo "   |  procesa_trans... |"
echo "   |-------------------|"
echo "   | READ ACCOUNTS     |"
echo "   | MATCH ID          |"
echo "   | VALIDATE SALDO    |"
echo "   | UPDATE RECORD     |"
echo "   +-------------------+"
echo "          ||"
echo "          \/"
echo "   accounts/TEMP.DAT"
echo "          ||"
echo "          \/"
echo "   +-------------------+"
echo "   | PATCH LAYER       |"
echo "   | patch_swap.sh     |"
echo "   | ATOMIC mv         |"
echo "   +-------------------+"
echo "          ||"
echo "          \/"
echo "   accounts/ACCOUNTS.DAT"
echo ""
echo "=============================="
echo "STATE: BATCH SYSTEM STABLE"
echo "MODE: SINGLE ACCOUNT CORE"
echo "=============================="
